name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - index.html
      - deployment.yaml
      - .github/workflows/docker-build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: zbruggen/argocd-demo:latest  # Replace with your Docker Hub username
