name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - index.html
      - .github/workflows/docker-build.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag from short SHA
        id: vars
        run: echo "tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zbruggen320/argocd-demo:${{ steps.vars.outputs.tag }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: zbruggen320/argocd-demo:.*|image: zbruggen320/argocd-demo:${{ steps.vars.outputs.tag }}|g" deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.tag }}"
          git push
